apiVersion: v1
kind: PersistentVolume
metadata:
  name: certificates-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /tmp/opensearch-certificates
    type: DirectoryOrCreate

