apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: os-data3
  name: os-data3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
