apiVersion: v1
data:
  opensearch.yml: |
    cluster.name: os-cluster
    network.host: 0.0.0.0

    bootstrap.memory_lock: "false" # disabled for k8s compatibility

    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: 93%
    cluster.routing.allocation.disk.watermark.high: 95%
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: os01
  name: os01-cm0
