apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: os01
  name: os01
spec:
  type: NodePort
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 30920
    - name: "9300"
      port: 9300
      targetPort: 9300
      nodePort: 30930
    - name: "9600"
      port: 9600
      targetPort: 9600
      nodePort: 30960
  selector:
    io.kompose.service: os01
